//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballLeague
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class fixture
    {
        [Key]
        [Display(Name = "Fixture")]
        public int fixture_id { get; set; }

        [Display(Name = "Location")]
        [Required(ErrorMessage = "Location Required")]
        public string location { get; set; }

        [Display(Name = "Team A")]
        [Required(ErrorMessage = "Team Required")]
        public string teamA { get; set; }

        [Display(Name = "Team B")]
        [Required(ErrorMessage = "Team Required")]
        public string teamB { get; set; }

        [Display(Name = "Score")]
        [Required(ErrorMessage = "Score Required")]
        public string score { get; set; }

        [Display(Name = "League")]
        [Required(ErrorMessage = "League Required")]
        public int league_id { get; set; }
    
        public virtual league league { get; set; }
    }
}
