//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballLeague
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class league_team
    {
        [Key]
        [Display(Name = "League")]
        public int league_id { get; set; }

        [Display(Name = "Team")]
        [Required(ErrorMessage = "Team Required")]
        public int team_id { get; set; }

        [Display(Name = "Match Played")]
        [Required(ErrorMessage = "Match Played Required")]
        public int match_played { get; set; }

        [Display(Name = "Wins")]
        [Required(ErrorMessage = "Wins Required")]
        public int win { get; set; }

        [Display(Name = "Loss")]
        [Required(ErrorMessage = "Loss Required")]
        public int loss { get; set; }

        [Display(Name = "Ties")]
        [Required(ErrorMessage = "Ties Required")]
        public int ties { get; set; }

        [Display(Name = "Points")]
        [Required(ErrorMessage = "points Required")]
        public int points { get; set; }
    
        public virtual league league { get; set; }
        public virtual team team { get; set; }
    }
}
