//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballLeague
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public player()
        {
            this.player_record = new HashSet<player_record>();
        }
        [Key]
        public int player_id { get; set; }

        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Full Name Required")]
        public string player_fullname { get; set; }

        [Display(Name = "Date OF Birth")]
        [Required(ErrorMessage = "Date OF Birth Required")]
        [DataType(DataType.Date)]
        public System.DateTime dob { get; set; }

        [Display(Name = "Position")]
        [Required(ErrorMessage = "Position Required")]
        public string position { get; set; }

        [Display(Name = "Nationality")]
        [Required(ErrorMessage = "Nationality Required")]
        public string nationality { get; set; }

        [Display(Name = "Team")]
        [Required(ErrorMessage = "Team Required")]
        public Nullable<int> team_id { get; set; }
    
        public virtual team team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<player_record> player_record { get; set; }
    }
}
