//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballLeague
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class player_record
    {
        [Key]
        public int record_id { get; set; }

        [Display(Name = "Plpayer Name")]
        [Required(ErrorMessage = "Player Name Required")]
        public int player_id { get; set; }

        [Display(Name = "Goal Socred")]
        [Required(ErrorMessage = "Goal Scored Required")]
        public int goal_scored { get; set; }

        [Display(Name = "Goal Assist")]
        [Required(ErrorMessage = "Goal Assist Required")]
        public int goal_assist { get; set; }
    
        public virtual player player { get; set; }
    }
}
