//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballLeague
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public team()
        {
            this.players = new HashSet<player>();
            this.league_team = new HashSet<league_team>();
        }
        [Key]
        public int team_id { get; set; }

        [Display(Name ="Team Name")]
        [Required(ErrorMessage ="Team Name Required")]
        public string team_name { get; set; }

        [Display(Name = "Short Name")]
        [Required(ErrorMessage = "Short Name Required")]
        public string short_name { get; set; }

        [Display(Name = "Location")]
        [Required(ErrorMessage = "Location Required")]
        public string location { get; set; }

        [Display(Name = "Owner Name")]
        [Required(ErrorMessage = "Owner Name Required")]
        public string owner_name { get; set; }

        [Display(Name = "Ground Name")]
        [Required(ErrorMessage = "Ground Name Required")]
        public string ground_name { get; set; }

        [Display(Name = "League Name")]
        [Required(ErrorMessage = "League Name Required")]
        public Nullable<int> league_id { get; set; }
    
        public virtual league league { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<player> players { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<league_team> league_team { get; set; }
    }
}
