//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballLeague
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [Key]
        public int user_id { get; set; }

        [Display(Name ="Full Name")]
        [Required(ErrorMessage ="Full Name Required")]
        public string user_fullname { get; set; }

        [Display(Name = "Email ")]
        [Required(ErrorMessage = "Email Required")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }

        [Display(Name = "Location ")]
        [Required(ErrorMessage = "Location Required")]
        public string location { get; set; }

        [Display(Name = "Password ")]
        [Required(ErrorMessage = "Password Required")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [Display(Name = "Gender ")]
        [Required(ErrorMessage = "Gender Required")]
        public string gender { get; set; }

        [Display(Name = "Favorite League ")]
        [Required(ErrorMessage = "Favorite League Required")]
        public int favorite_league { get; set; }

        [Display(Name = "User Status")]
        [Required(ErrorMessage = "User Status Required")]
        public int u_status { get; set; }

        [Display(Name = "ROll")]
        [Required(ErrorMessage = "Roll  Required")]
        public int u_roleID { get; set; }

        [Display(Name = "Username ")]
        [Required(ErrorMessage = "username Required")]
        public string username { get; set; }
    
        public virtual role role { get; set; }
        public virtual league league { get; set; }
    }
}
